30-removable-emails
js-tasks-ru/vue-20240627_anton494 pull request #11
Opened 2024-09-16 09:17 UTC by anton8739

2024-09-16 09:17 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-09-18 22:54 UTC, ShGKme requested changes
Хотя решение работает без этого, все события лучше явно описать в `emits`, как и пропсы.

В противном случае у компонента не задокументированы события, о них не знает IDE и TypeScript, а также есть риск конфликта (двойного срабатывания) в случае событий, совпадающих с DOM событиями.

2024-09-27 08:40 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-01 22:02 UTC, ShGKme approved these changes

2024-10-01 22:03 UTC, merged